CUDA_VISIBLE_DEVICES=0 python /root/LLaMA-Factory/src/train_bash.py \
    --stage sft \
    --model_name_or_path /root/autodl-tmp/models/ZhipuAI/chatglm3-6b \
    --predict_with_generate True \
    --checkpoint_dir /root/LLaMA-Factory/output1120 \
    --finetuning_type lora \
    --template chatglm3 \
    --dataset_dir /root/LLaMA-Factory/data \
    --dataset oaast_rm \
    --max_samples 1000 \
    --per_device_eval_batch_size 2 \
    --max_new_tokens 350 \
    --top_k 10 \
    --top_p 0.5 \
    --temperature 0.01 \
    --output_dir ./output1121_glm3 \
    --fp16 True \
    --do_predict True